<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU30Y6QJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU30Y6QJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU30Y6QJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU30Y6QJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU30Y6QJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'U30Y6QJ',
    'container.build_id' => '56b3e17b',
    'container.build_time' => 1599812144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU30Y6QJ');
