<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEDY5POD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEDY5POD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEDY5POD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEDY5POD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEDY5POD\App_KernelDevDebugContainer([
    'container.build_hash' => 'EDY5POD',
    'container.build_id' => 'ccc4f86e',
    'container.build_time' => 1599206283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEDY5POD');
